### ISSUE TITLE
Service.MotionSensor support

### ISSUE THREAD

**Issue by leoneleone** [steedferns/homebridge-huesensors#1]
Can you please add to the code so that the hue sensors also show up in HomeKit as actual motion sensors? It's great to have them as switches too - the ability to turn them off and on is useful. Ultimately I'd like to use the motion detected info as triggers in HomeKit

**Comment by steedferns** [comment]
I don't think that would be possible at this time.  There are no webhooks for when a sensor triggers from the Hue API.

**Comment by steedferns** [comment]
It looks like this functionality has been implemented now in https://github.com/ebaauw/homebridge-hue
