### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by fynnit** [steedferns/homebridge-huesensors#2]
could you be more precise in your readme?
i copied your smaples-config in my config, but switching one switch of doesnt affect (any of my 2) sensors... how do i add both sensors?

**Comment by steedferns** [comment]
Please paste the huesensors section in your config.

**Comment by fynnit** [comment]
i got it to work but the switch on my iphone isnt updating its status after i switch them off. ist jumping to on after about 5 seconds. in the hue app the sensors are still off though. any clues?

**Comment by steedferns** [comment]
I fixed the status issue with the build uploaded last night.  Please update.  Note: You need to specify the sensor names in the config file now.  This is for more granular control.

**Comment by fynnit** [comment]
awesome! i will update my version tonight (7pm est) and come back to you with the result. 

thank you!

**Comment by fynnit** [comment]
ok so i updated my config with the filters and created a second accessory with the filters added.
everything runs smoothly now! thank you so much!! 

cheers

**Comment by steedferns** [comment]
Strange. I just tested it without any issue. Can you paste your config? Also, did you obtain a username from your bridge?
