### ISSUE TITLE
 "username": "bridge username"

### ISSUE THREAD

**Issue by christophedelanghe** [steedferns/homebridge-huesensors#3]
What is the "bridge username"? Thanks in advance!

**Comment by bkarakashev** [comment]
yeah, what is the bridge username?

**Comment by bkarakashev** [comment]
@christophedelanghe if you still looking for the "bridge username" you will need to generate API token.
You can find how in this URLs:
https://developers.meethue.com/develop/get-started-2/
https://www.sitebase.be/generate-phillips-hue-api-token/
